// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9NaxsHYSyw8PED5MVNH_xaJ0huPWQod8',
    appId: '1:760263151467:web:c1b6a8517ca2bbd6f4c62e',
    messagingSenderId: '760263151467',
    projectId: 'dormdeals-5b396',
    authDomain: 'dormdeals-5b396.firebaseapp.com',
    storageBucket: 'dormdeals-5b396.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRTtT1eK5jGl0gJZ7WaBD7FKcLEfsnSWI',
    appId: '1:760263151467:android:189a102cb2c4a519f4c62e',
    messagingSenderId: '760263151467',
    projectId: 'dormdeals-5b396',
    storageBucket: 'dormdeals-5b396.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAB1jsawZKgMMK_NNx8oQZlleezB6jA9Hk',
    appId: '1:760263151467:ios:00e4aa3283b9dc45f4c62e',
    messagingSenderId: '760263151467',
    projectId: 'dormdeals-5b396',
    storageBucket: 'dormdeals-5b396.firebasestorage.app',
    iosBundleId: 'com.tanvir.comp3130.dormDeals',
  );
}
